# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 08:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDevList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bindtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u7ed1\u5b9a\u65f6\u95f4')),
            ],
            options={
                'db_table': 'bindlist',
                'verbose_name': '\u7528\u6237\u8bbe\u5907\u5217\u8868',
                'verbose_name_plural': '\u7528\u6237\u8bbe\u5907\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='AppFriendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('isfriend', models.BooleanField(default=False, verbose_name='\u5df2\u7ecf\u662f\u597d\u53cb?')),
            ],
            options={
                'verbose_name': '\u597d\u53cb\u5217\u8868',
                'verbose_name_plural': '\u597d\u53cb\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('uname', models.CharField(max_length=64, unique=True, verbose_name='\u6635\u79f0')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='\u90ae\u7bb1')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('key', models.CharField(max_length=64, verbose_name='\u5bc6\u94a5')),
                ('uuid', models.UUIDField(default=b'e38db5adec594f838a0d54def861388d', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='\u7528\u6237ID')),
                ('regip', models.GenericIPAddressField(editable=False, verbose_name='\u6ce8\u518cIP')),
                ('regtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='\u914d\u7f6e\u4fe1\u606f')),
                ('phone_active', models.BooleanField(default=False, verbose_name='\u624b\u673a\u5df2\u9a8c\u8bc1')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7ba1\u7406',
                'verbose_name_plural': '\u7528\u6237\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('mac', models.CharField(max_length=17, unique=True, verbose_name='\u7f51\u5361\u5730\u5740')),
                ('key', models.CharField(max_length=8, verbose_name='\u5bc6\u7801')),
                ('appkey', models.CharField(max_length=8, unique=True, verbose_name='APP\u5bc6\u7801')),
                ('uuid', models.UUIDField(default=b'994475e645294be6aa222a95908e1051', primary_key=True, serialize=False, unique=True, verbose_name='\u8bbe\u5907ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='\u540d\u79f0')),
                ('regtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u7ba1\u7406',
                'verbose_name_plural': '\u8bbe\u5907\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='MqttAcl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow', models.IntegerField(verbose_name='\u5141\u8bb8')),
                ('ipaddr', models.GenericIPAddressField(null=True, verbose_name='IP\u5730\u5740')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='\u7528\u6237\u540d')),
                ('clientid', models.CharField(max_length=100, null=True, verbose_name='\u5ba2\u6237\u7aefID')),
                ('access', models.IntegerField(verbose_name='\u8bbf\u95ee\u7ea7\u522b')),
                ('topic', models.CharField(max_length=100, verbose_name='\u4e3b\u9898')),
            ],
            options={
                'db_table': 'mqtt_acl',
                'verbose_name': '\u8bbf\u95ee\u5217\u8868',
                'verbose_name_plural': '\u8bbf\u95ee\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='MqttUser',
            fields=[
                ('is_superuser', models.BooleanField(default=False, verbose_name='\u8d85\u7ea7\u7528\u6237')),
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='\u7528\u6237ID')),
                ('password', models.CharField(max_length=64, verbose_name='\u7528\u6237\u5bc6\u7801')),
                ('salt', models.CharField(max_length=32, null=True, verbose_name='\u52a0\u76d0')),
            ],
            options={
                'db_table': 'mqtt_user',
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.CreateModel(
            name='SharedDevList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isshared', models.BooleanField(default=False, verbose_name='\u5206\u4eab\u6210\u529f?')),
                ('guest', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='user_manager.AppUser', verbose_name='\u5206\u4eab')),
                ('host', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='host_user', to='user_manager.AppUser', verbose_name='\u6240\u6709\u8005')),
                ('sdevice', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='user_manager.Devices', verbose_name='\u8bbe\u5907')),
            ],
            options={
                'db_table': 'devices_shared',
                'verbose_name': '\u5206\u4eab\u8bbe\u5907',
                'verbose_name_plural': '\u5206\u4eab\u8bbe\u5907',
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otpuuid', models.UUIDField(verbose_name='\u4e00\u6b21\u6027ID')),
                ('bodydata', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='\u6570\u636e')),
                ('sharedev', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='user_manager.Devices', verbose_name='\u8bbe\u5907')),
                ('sharer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='user_manager.AppUser', verbose_name='\u5206\u4eab\u8005')),
            ],
            options={
                'db_table': 'share_request',
                'verbose_name': '\u5206\u4eab\u94fe\u63a5',
                'verbose_name_plural': '\u5206\u4eab\u94fe\u63a5',
            },
        ),
        migrations.CreateModel(
            name='SmsErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField(null=True, verbose_name='IP\u5730\u5740')),
                ('addtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u65f6\u95f4')),
                ('phone', models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7\u7801')),
            ],
            options={
                'db_table': 'smserr_log',
                'verbose_name': '\u77ed\u4fe1\u9519\u8bef',
                'verbose_name_plural': '\u77ed\u4fe1\u9519\u8bef',
            },
        ),
        migrations.CreateModel(
            name='SmsErrorTable',
            fields=[
                ('errcode', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u9519\u8bef\u7801')),
                ('msg', models.CharField(max_length=100, verbose_name='\u9519\u8bef\u63cf\u8ff0')),
            ],
            options={
                'db_table': 'smserrcode',
                'verbose_name': '\u53d1\u9001\u77ed\u4fe1\u9519\u8bef\u7801',
            },
        ),
        migrations.CreateModel(
            name='SrvList',
            fields=[
                ('ipaddr', models.GenericIPAddressField(primary_key=True, serialize=False, verbose_name='\u670d\u52a1\u5668IP')),
                ('port', models.IntegerField(default=1883, verbose_name='\u7aef\u53e3')),
                ('mver', models.CharField(max_length=16, verbose_name='\u670d\u52a1\u5668\u7248\u672c')),
                ('pubkey', models.TextField(max_length=2048, verbose_name='\u670d\u52a1\u5668\u516c\u94a5')),
                ('http_user', models.CharField(default='admin', max_length=32, verbose_name='Web\u7528\u6237\u540d')),
                ('http_pass', models.CharField(default='public', max_length=32, verbose_name='Web\u5bc6\u7801')),
                ('concount', models.IntegerField(verbose_name='\u7528\u6237\u8fde\u63a5\u6570')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668\u7ba1\u7406',
                'verbose_name_plural': '\u670d\u52a1\u5668\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='smserrorlog',
            name='errcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.SmsErrorTable', verbose_name='\u9519\u8bef\u7801'),
        ),
        migrations.AlterUniqueTogether(
            name='mqttacl',
            unique_together=set([('id',)]),
        ),
        migrations.AlterUniqueTogether(
            name='devices',
            unique_together=set([('uuid', 'mac')]),
        ),
        migrations.AlterUniqueTogether(
            name='appuser',
            unique_together=set([('email', 'phone', 'uuid', 'uname')]),
        ),
        migrations.AddField(
            model_name='appfriendlist',
            name='friend',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='friend_user', to='user_manager.AppUser', verbose_name='\u597d\u53cb\u540d'),
        ),
        migrations.AddField(
            model_name='appfriendlist',
            name='my_uuid',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='user_manager.AppUser', verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='appdevlist',
            name='appid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manager.AppUser', verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='appdevlist',
            name='devid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manager.Devices', verbose_name='\u8bbe\u5907'),
        ),
        migrations.AlterUniqueTogether(
            name='appfriendlist',
            unique_together=set([('my_uuid', 'friend')]),
        ),
        migrations.AlterUniqueTogether(
            name='appdevlist',
            unique_together=set([('appid', 'devid')]),
        ),
    ]
